[#21] TOKENIZERS_PARALLELISM set to True. To avoid warning.
eubinecto/wisdomify pull request #23
Opened 2021-07-12 13:57 UTC by ArtemisDicoTiar

[#21] tokenizer parallelism warning removed.

2021-07-13 12:04 UTC, eubinecto requested changes
수정이 필요할듯!

2021-07-13 12:20 UTC, ArtemisDicoTiar commented on wisdomify/main/__init__.py
> +os.environ["TOKENIZERS_PARALLELISM"] = "true"
오케이
나도 찾아보니깐 저렇게 수정하면 워닝자체는 사라지는 데 정석대로 수정하려면 토크나이저를 포크 전에 사용하지 않아야한다고 하더라고 
저거 데이터셋 클래스 한번 수정해볼게

2021-07-14 02:38 UTC, eubinecto commented on wisdomify/main/__init__.py
> +os.environ["TOKENIZERS_PARALLELISM"] = "true"
종윤쓰의 분석: https://github.com/eubinecto/wisdomify/issues/21#issuecomment-879107099
오케이, 일단 내가 브랜치들어가서 확인해보겠으.

2021-07-14 03:28 UTC, eubinecto commented on wisdomify/main/__init__.py
> +os.environ["TOKENIZERS_PARALLELISM"] = "true"
## hugging face tokenizer에서  멀티 프로세싱이 필요한 이유?
corpus -> tokenize -> X, y tensor를 빌드하기 위해 쓰이는데, 이 corpus 사이즈가 커지면 하나의 프로세스로는 역부족일 것.
물론 지금은 데이터가 쥐꼬리만해서 큰 필요는 없지만... 데이터가 커지만 토크나이징만 한두시간이 걸릴 수 가 있다.

## DataLoader에서 멀티 프로세싱이 필요한 이유?
하나의 배치를 처리하는 동안 다음 배치를 로드를 미리하고 있으면 시간을 아낄 수 있다. 

## 해결방안?
두 작업모두 멀티프로세싱이 필요하다. 하지만 두 작업 모두 멀티프로세싱을 쓰면 오류가 날 가능성이 높아진다.
그러면 **두 작업을 따로 진행하자.** 즉,
1. corpus -> tokenizer (멀티 프로세스) -> X, y tensors -> 로컬에 저장. ([torch.save() 사용](https://pytorch.org/docs/stable/generated/torch.save.html))
2. 로컬에서 X, y tensors 로드 -> data loader

2021-07-14 03:34 UTC, eubinecto commented
closes #21

2021-07-14 03:34 UTC, merged